{% set name = "pngquant" %}
{% set version = "2.16.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/kornelski/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 6b186b76bc995ee12949a48a1041173459eb8050ef1dceb5f7ba43726327b1ea

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - libimagequant
    - lcms2
    - libpng

test:
  commands:
    - pngquant --version

about:
  home: https://pngquant.org/
  license: GPL-3.0-or-later
  license_file: COPYRIGHT
  summary: 'Lossy PNG compressor — pngquant command based on libimagequant library '

extra:
  recipe-maintainers:
    - izahn
